---
title: "LMER"
author: "Alberte Baggesgaard Seeberg"
date: "3/22/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
setwd("~/Desktop/Bachelor CogSci/5. semester/Bachelor/Data/Bachelor")

#Loading packages
library(stringr)
library(plyr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(hellno)
library(apaTables)
library(MuMIn)
library(lme4)
library(yarrr)
```

## READ DATA + CHANGE VARIABLES
```{r}
CIData = read.csv("CIData.csv")
CIData = CIData[-1]

CIData$RawPercentScore = as.character(CIData$RawPercentScore)
CIData$ChanceCorrected = as.character(CIData$ChanceCorrected)
CIData$Condition = as.character(CIData$Condition)
CIData$Deviant = as.character(CIData$Deviant)
CIData$DeviantLevel = as.numeric(CIData$DeviantLevel)
CIData$Dato = as.character(CIData$Dato)
CIData$Køn = as.character(CIData$Køn)
CIData$DatoOp1 = as.character(CIData$DatoOp1)
CIData$DatoOp2 = as.character(CIData$DatoOp2)
CIData$TaleTelefon = as.character(CIData$TaleTelefon)
CIData$TinnitusPre = as.character(CIData$TinnitusPre)
CIData$TinnitusPost = as.character(CIData$TinnitusPost)
CIData$Hoereapparat = as.character(CIData$Hoereapparat)
CIData$Musikviden = ordered(CIData$Musikviden, levels = c("1","2","3","4","5"))
CIData$Musikglaede=ordered(CIData$Musikglaede, levels = c("1", "2", "3", "4", "5", "6","7"))

```

## PREPARING DATA FOR LMER
```{r}

#Making a data frame from the CIData, containing only these variables
CIPlot=aggregate(CIData$Correct,list(CIData$ID), mean)

CIPlot=plyr::rename(CIPlot, c("Group.1"="ID"))
CIPlot=plyr::rename(CIPlot, c("x"="AvCor"))



CI=merge(CIPlot,unique(CIData[c("ID","Condition","AlderOP","Lyttevaner",
                                "AarUdenHoerelse", "Musikviden",
                                "Musikglaede" )]),by="ID")

CI$AvCor = CI$AvCor*100

```

## MODELS
```{r}

m0=lmer(AvCor~1+(1|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

m1=lmer(AvCor~AarUdenHoerelse+(1+AarUdenHoerelse|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
#summary(m1)

m1a=lmer(AvCor~AlderOP+(1+AlderOP|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

m1b=lmer(AvCor~Lyttevaner+(1+Lyttevaner|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

m1c=lmer(AvCor~Musikglaede+(1+Musikglaede|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

m1d=lmer(AvCor~Musikviden+(1+Musikviden|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

m2=lmer(AvCor~AarUdenHoerelse+AlderOP+(1+AlderOP|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
#summary(m2)

m3=lmer(AvCor~AarUdenHoerelse+AlderOP+Lyttevaner+(1+Lyttevaner|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
#summary(m3)

m4=lmer(AvCor~AarUdenHoerelse+AlderOP+Lyttevaner+Musikglaede+(1+Musikglaede|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
#summary(m4)

m5=lmer(AvCor~AarUdenHoerelse+AlderOP+Lyttevaner+Musikglaede+Musikviden+(1+Musikviden|Condition), data=CI, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
#summary(m5)

anova(m0,m1,m2,m3,m4,m5)

anova(m0,m5)

anova(m0,m1)
anova(m0,m1a)
anova(m0,m1b)
anova(m0,m1c)
anova(m0,m1d)


```

## PLOTS
```{r}

ggplot(CI, aes(x = AarUdenHoerelse, y = AvCor, color = Condition)) +
  geom_point() +
  geom_smooth(method='lm',formula=y~x)

ggplot(CI, aes(x = AlderOP, y = AvCor, color = Condition)) +
  geom_point() +
  geom_smooth(method='lm',formula=y~x)

ggplot(CI, aes(as.numeric(Lyttevaner), AvCor, color=Condition))+geom_point()+geom_smooth(method=glm)

ggplot(CI, aes(as.numeric(Musikviden), AvCor, color=Condition))+geom_point()+geom_smooth(method=glm)

ggplot(CI, aes(as.numeric(Musikglaede), AvCor, color=Condition))+geom_point()+geom_smooth(method=glm)

```

